import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MIME = { '.html':'text/html', '.js':'text/javascript', '.css':'text/css' };
const server = http.createServer(async (req,res)=>{ let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/')p='/index.html'; const fp=path.join(ROOT,p); if(!existsSync(fp)){res.writeHead(404);res.end();return;} res.writeHead(200,{'Content-Type':MIME[path.extname(fp)]||'application/octet-stream'}); res.end(await readFile(fp)); });
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const port = server.address().port;
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const b = await chromium.launch({ headless:true, args:['--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--enable-unsafe-swiftshader'] });
const pg = await b.newPage({ viewport:{ width:1200, height:700 } });
const ev=(fn,...a)=>pg.evaluate(fn,...a);
await pg.goto(`http://127.0.0.1:${port}/index.html?test=1`, { waitUntil:'load' });
await pg.waitForFunction(()=>window.__booted===true,{timeout:5000});
await pg.fill('#nameInput','我'); await pg.fill('#roomInput','demo'); await pg.click('#joinBtn');
await pg.waitForFunction(()=>window.__test&&window.__test.joined(),{timeout:5000});
await ev(()=>{ window.__test.recv({type:'state',from:'a',name:'小红',color:0xf72585,x:14,y:1.6,z:-9,yaw:0.5,pitch:0,wid:'rifle',hp:90,alive:true,kills:1,deaths:0});
  window.__test.recv({type:'state',from:'c',name:'小刚',color:0x4cc9f0,x:21,y:1.6,z:-7,yaw:-0.6,pitch:0,wid:'sniper',hp:100,alive:true,kills:0,deaths:0}); });
await ev(()=>window.__test.weapon(2));
await sleep(500);
await pg.screenshot({ path: path.join(__dirname,'shot-wave1.png') });
console.log('shot written');
await b.close(); server.close();
